trigger:
  - main

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main

pool:
  vmImage: windows-latest

variables:
- group: vg-costs-cli

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: "sc-costcli-wif"
      scriptType: powershell
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Subscription ID: $(subscriptionId)"
        dotnet tool install -g azure-cost-cli
        azure-cost accumulatedCost -s "$(subscriptionId)" -o markdown > azure-cost-report.md
        azure-cost accumulatedCost -s "$(subscriptionId)"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'azure-cost-report.md'
      artifactName: 'AzureCosts'
